name: Replace part of an image (Inpaint)
description: Select and replace anything in an image (FLUX)
tip: |-
  This workflow edits a specific region in the given image by first applying the masking prompt to highlight a specific region of the image, and then applying the inpainting prompt to fill (re-draw) in the highlighted region. Use this tool when a user requests changes to a specific object or region in an image.
thumbnail: app/flux-inpaint-opt.mp4
cost_estimate: 3 * n_samples
output_type: image
handler: comfyui
status: prod
base_model: flux-dev
comfyui_output_node_id: 181
comfyui_intermediate_outputs:
  inpaint_preview: 206
parameters:
  image:
    type: image
    label: Image
    description: Input image
    required: true
    comfyui:
      node_id: 53
      field: inputs
      subfield: image
  masking_prompt:
    type: string
    label: Region prompt
    description: |-
      Description (just one or a few words) of what object / region you want to replace / inpaint.
    tip: |-
      This prompt will be used to highlight the object/region to inpaint, creating a mask. Try to make this prompt as short, clean and simple as possible. use single words instead of full sentences. Some examples of good masking prompts are 'face', 'building', 'hair, headwear, hat', ...
    required: false
    comfyui:
      node_id: 66
      field: inputs
      subfield: value
  inpainting_prompt:
    type: string
    label: Inpainting prompt
    description: |-
      A prompt describing what you want to replace the masked region with. No need to describe the entire scene, just the object or region you want to generate.
    required: true
    comfyui:
      node_id: 67
      field: inputs
      subfield: value
  resolution:
    type: integer
    label: Resolution
    description: The resolution at which the inpainted region is generated.
    tip: Can be adjusted to somewhat match the input resolution of the given image.
    default: 1024
    minimum: 512
    maximum: 1536
    step: 64
    comfyui:
      node_id: 74
      field: inputs
      subfield: value
  mask_image:
    type: image
    label: Mask Image
    description: |-
      Optionally provide a mask image yourself (white regions will get inpainted). To activate the mask image, make sure your masking prompt is empty!!
    comfyui:
      node_id: 48
      field: inputs
      subfield: image
  creativity:
    type: float
    label: AI creativity
    description: |-
      How much the surrounding scene influences the inpainting. Recommended values 0.7-0.9
    tip: |-
      This controls how much the inpainting looks at the surrounding (fixed) content in the image. Lower values can produce more creative outputs that have better prompt adherence but they often tend to look misplaced and out of context with the rest of the scene.
    default: 0.85
    minimum: 0.0
    maximum: 1.1
    step: 0.01
    comfyui:
      node_id: 226
      field: inputs
      subfield: strength
  mask_expand:
    type: integer
    label: Expand the inpainting mask slightly
    description: Make the inpainting region slightly larger to make the results more realistic
    tip: |-
      The default is typically fine. If the masking prompt is targetting a small object, but the inpainting object is something larger, you may want to increase this value to give the inpainting model enough space to draw the new thing. If the inpainting region needs to be very precise you can very rarely decrease this value to eg 24.
    default: 12
    minimum: 0
    maximum: 64
    comfyui:
      node_id: 190
      field: inputs
      subfield: expand
  mask_blur:
    type: integer
    label: Blur the inpainting mask at the edges
    description: |-
      Making the inpainting region blurry at the edges can make the results slightly better
    tip: |-
      The default is typically fine. If the mask has lots of fine edges, you can consider tuning this down to avoid erasing the details in the mask.
    default: 24
    minimum: 0
    maximum: 160
    comfyui:
      node_id: 191
      field: inputs
      subfield: amount
  seed:
    type: integer
    label: Seed
    description: Set random seed for reproducibility. If blank, will be set randomly.
    tip: |-
      You should only set this if you want to start from/copy the seed of a previous image. Unless one is specified, you should leave this blank!
    default: random
    minimum: 0
    maximum: 2147483647
    comfyui:
      node_id: 65
      field: inputs
      subfield: seed
  n_samples:
    type: integer
    label: Number of samples
    description: Number of samples to generate
    tip: |-
      This is the number of tries to generate with different noise. You always keep all settings fixed when doing multiple samples.
    default: 1
    minimum: 1
    maximum: 4
